/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raspberry;

import com.pi4j.io.gpio.GpioController;
import com.pi4j.io.gpio.GpioFactory;
import com.pi4j.io.gpio.GpioPinDigitalOutput;
import com.pi4j.io.gpio.GpioPinPwmOutput;
import com.pi4j.io.gpio.Pin;
import com.pi4j.io.gpio.PinState;
import com.pi4j.io.gpio.RaspiPin;
import com.pi4j.util.CommandArgumentParser;
import com.raspberry.exceptions.RaspistillException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author dustin
 */
public class GeneralPiController extends javax.swing.JFrame {

    /**
     * Creates new form GeneralPiController
     */
    public GeneralPiController() {
        initComponents();
        setSize(1040, 670);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        onButton = new javax.swing.JButton();
        offButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        cameraButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setLayout(new java.awt.BorderLayout());

        onButton.setText("ON");
        onButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonActionPerformed(evt);
            }
        });
        jPanel3.add(onButton);

        offButton.setText("OFF");
        offButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offButtonActionPerformed(evt);
            }
        });
        jPanel3.add(offButton);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jButton25.setText("PWM");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton25);

        jTextField1.setText("jTextField1");
        jPanel4.add(jTextField1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jDialog1.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        numberLabel.setText("jLabel2");
        jDialog1.getContentPane().add(numberLabel, java.awt.BorderLayout.PAGE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jButton1.setText("3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(670, 95, 40, 20);

        jButton2.setText("5");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 120, 40, 20);

        jButton3.setText("7");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(670, 150, 40, 20);

        jButton4.setText("11");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(670, 200, 46, 20);

        jButton5.setText("13");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(670, 225, 46, 20);

        jButton6.setText("15");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(670, 250, 46, 20);

        jButton7.setText("19");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(670, 300, 46, 20);

        jButton8.setText("21");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(670, 330, 46, 20);

        jButton9.setText("23");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(670, 360, 46, 20);

        jButton10.setText("29");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(670, 430, 46, 20);

        jButton11.setText("31");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(670, 460, 46, 20);

        jButton12.setText("33");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(670, 490, 46, 20);

        jButton13.setText("35");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(670, 515, 46, 20);

        jButton14.setText("37");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(670, 540, 46, 20);

        jButton15.setText("12");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(724, 200, 46, 20);

        jButton16.setText("16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(724, 250, 46, 20);

        jButton17.setText("18");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(724, 280, 46, 20);

        jButton18.setText("22");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(724, 330, 46, 20);

        jButton19.setText("24");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(724, 360, 46, 20);

        jButton20.setText("26");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(724, 380, 46, 20);

        jButton21.setText("32");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(724, 460, 46, 20);

        jButton22.setText("36");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(724, 510, 46, 20);

        jButton23.setText("38");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(724, 535, 46, 20);

        jButton24.setText("40");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);
        jButton24.setBounds(724, 560, 46, 20);

        cameraButton.setText("camera");
        cameraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cameraButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cameraButton);
        cameraButton.setBounds(20, 280, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 600);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardImage.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1006, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final JButton button = (JButton) evt.getSource();
        System.out.println((button.getText()));
        numberLabel.setText(button.getText());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void onButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonActionPerformed
        final String index = numberLabel.getText();
        GpioPinDigitalOutput pin = indexToGpioPin.get(index);
        if (pin == null) {
            pin = gpio.provisionDigitalOutputPin(indexToPinMap.get(index), "MyLED", PinState.HIGH);
            pin.setShutdownOptions(true, PinState.LOW);
            indexToGpioPin.put(index, pin);
        } else {
            pin.high();
        }
    }//GEN-LAST:event_onButtonActionPerformed

    private void offButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offButtonActionPerformed
        final String index = numberLabel.getText();
        GpioPinDigitalOutput pin = indexToGpioPin.get(index);
        if (pin != null) {
            pin.low();
        }
    }//GEN-LAST:event_offButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        gpio.shutdown();
    }//GEN-LAST:event_formWindowClosing

    private void cameraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cameraButtonActionPerformed
        RPiCamera piCamera = null;
        // Attempt to create an instance of RPiCamera, will fail
        // if raspistill is not properly installed
        try {
            String saveDir = "/home/pi/Desktop";
            piCamera = new RPiCamera(saveDir);

            // Take a still image, buffer, and save it
            if (piCamera != null) {
                try {
                    piCamera.takeStill("Picture");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (RaspistillException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cameraButtonActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        final String index = numberLabel.getText();
        GpioPinDigitalOutput gpin = indexToGpioPin.get(index);
        if (gpin == null) {
            Pin pin = CommandArgumentParser.getPin(
                    RaspiPin.class, // pin provider class to obtain pin instance from
                    indexToPinMap.get(index), // default pin if no pin argument found
                    new String[]{});             // argument array to search in

            GpioPinPwmOutput pwm = gpio.provisionPwmOutputPin(pin);

            // you can optionally use these wiringPi methods to further customize the PWM generator
            // see: http://wiringpi.com/reference/raspberry-pi-specifics/
            com.pi4j.wiringpi.Gpio.pwmSetMode(com.pi4j.wiringpi.Gpio.PWM_MODE_MS);
            com.pi4j.wiringpi.Gpio.pwmSetRange(1000);
            com.pi4j.wiringpi.Gpio.pwmSetClock(500);

            pwm.setPwm(500);
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(GeneralPiController.class.getName()).log(Level.SEVERE, null, ex);
            }
            pwm.setPwm(0);

        } else {
            gpin.low();
        }


    }//GEN-LAST:event_jButton25ActionPerformed

    GpioController gpio = GpioFactory.getInstance();

    private static Map<String, Pin> indexToPinMap = new HashMap<>();
    private static Map<String, GpioPinDigitalOutput> indexToGpioPin = new HashMap<>();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralPiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralPiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralPiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralPiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        indexToPinMap.put("3", RaspiPin.GPIO_02);
        indexToPinMap.put("5", RaspiPin.GPIO_03);
        indexToPinMap.put("7", RaspiPin.GPIO_04);
        indexToPinMap.put("11", RaspiPin.GPIO_17);
        indexToPinMap.put("12", RaspiPin.GPIO_18);
        indexToPinMap.put("13", RaspiPin.GPIO_27);
        indexToPinMap.put("15", RaspiPin.GPIO_22);
        indexToPinMap.put("16", RaspiPin.GPIO_23);
        indexToPinMap.put("18", RaspiPin.GPIO_24);
        indexToPinMap.put("19", RaspiPin.GPIO_10);
        indexToPinMap.put("21", RaspiPin.GPIO_09);
        indexToPinMap.put("22", RaspiPin.GPIO_25);
        indexToPinMap.put("23", RaspiPin.GPIO_11);
        indexToPinMap.put("24", RaspiPin.GPIO_08);
        indexToPinMap.put("26", RaspiPin.GPIO_07);
        indexToPinMap.put("29", RaspiPin.GPIO_05);
        indexToPinMap.put("31", RaspiPin.GPIO_06);
        indexToPinMap.put("32", RaspiPin.GPIO_12);
        indexToPinMap.put("33", RaspiPin.GPIO_13);
        indexToPinMap.put("35", RaspiPin.GPIO_19);
        indexToPinMap.put("36", RaspiPin.GPIO_16);
        indexToPinMap.put("37", RaspiPin.GPIO_26);
        indexToPinMap.put("38", RaspiPin.GPIO_20);
        indexToPinMap.put("40", RaspiPin.GPIO_21);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralPiController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cameraButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JButton offButton;
    private javax.swing.JButton onButton;
    // End of variables declaration//GEN-END:variables
}
